title: Public Policy Blog
email: your-email@example.com
description: A blog about policy, governance, and society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reallyishan009.github.io" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-feed
